export const SET_NAMES_DATA = 'SET_NAMES_DATA';
export const SET_INPUT_VALUE = 'SET_INPUT_VALUE';
export const SET_SELECTED_NAME = 'SET_SELECTED_NAME';
export const REMOVE_SELECTED_NAME = 'REMOVE_SELECTED_NAME';